config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admins

  root 'home#index'
  get 'home/index'
  get 'apidoc', to: "application#apidoc"

  
  namespace :admin do
    get 'home/index'
    get 'home/admins'
    get 'home/dashboard'
    root :to => "home#index"
    resources :admins do
    end
  end

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/admins_controller.rb
class Admin::AdminsController < ApplicationController
  def index
    @admins = Admin.page(params[:page]).per(5)

    respond_to do |format|
      format.json  {
        render :json => {
          data: @admins,
          pageInfo: {
            totalPages: @admins.total_pages,
            currentPage: params[:page] || 1,
            windowSize: 3
          }
        }
      }
    end
  end

  def create
    @admin = Admin.new(admin_params)
    if @admin.save
      respond_to do |format|
        format.json  {
          render :json => {
            messages: [
              {
                content: "Created admin successfully",
                type: "success"
              }
            ]
          }
        }
      end
    else
      if @admin.errors.messages.values
        messages = @admin.errors.full_messages.map do |message|
          {
            content: message,
            type: "error"
          }
        end
      end

      respond_to do |format|
        format.json  {
          render :json => {
            messages: messages
          }
        }
      end
    end
  end

  private 

  def admin_params
    params_admin = params.require(:admin)
    params_admin.permit(:email, :password, :password_confirmation)
  end

end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  layout 'admin'

end

app/controllers/admin/home_controller.rb
class Admin::HomeController < Admin::BaseController
  before_action :authenticate_admin!
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def dashboard
    respond_to do |format|
      format.js do
      end
    end
  end

  def admins
    respond_to do |format|
      format.js do
      end
    end
  end
end

app/helpers/admin/admins_helper.rb
module Admin::AdminsHelper
end

app/helpers/admin/home_helper.rb
module Admin::HomeHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admin/admins/index.html.slim
h1 Admin::Admins#index
p Find me in app/views/admin/admins/index.html.slim

app/views/admin/home/_admins.html.slim
h1 Admins
= react_component('TEST.Admin.AdminIndex', {admins: []})

app/views/admin/home/_dashboard.html.slim
h1 Test dashboard page

app/views/admin/home/admins.js.erb
$(".main-container").fadeIn().html("<%= escape_javascript(render 'admin/home/admins') %>");
ReactRailsUJS.mountComponents()
var adminsService = new TEST.Admin.AdminsService
adminsService.fetchAdmins(1)

app/views/admin/home/dashboard.js.erb
$(".main-container").fadeIn().html("<%= escape_javascript(render 'admin/home/dashboard') %>");

app/views/admin/home/index.html.slim
= react_component('TEST.Admin.App', {})

app/views/home/index.html.slim
h1 Welcome
p Hello TEST

app/views/layouts/admin.html.slim
doctype html
html
  head
    title TEST Admin
    / link rel="icon" type="image/png" href="#{asset_path('favicon.png')}"
    meta content="IE=edge" http-equiv="X-UA-Compatible"
    meta content="width=device-width, initial-scale=1.0, user-scalable=no" name="viewport"


    = stylesheet_link_tag    'application', media: 'all','data-turbolinks-track' => 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track' => 'reload'
    = favicon_link_tag 'common/favicon.ico'
    = csrf_meta_tags

  body.admin
    #header.ui.containter
      = render 'shared/admin/header'
    #page-container.ui.container.segment.main-container
      = yield
    #footer
      = render 'shared/admin/footer'
  = yield(:js)

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AltFluxTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.slim
doctype html
html
  head
    title TEST
    / link rel="icon" type="image/png" href="#{asset_path('favicon.png')}"
    meta content="IE=edge" http-equiv="X-UA-Compatible"
    meta content="width=device-width, initial-scale=1.0, user-scalable=no" name="viewport"


    = stylesheet_link_tag    'application', media: 'all','data-turbolinks-track' => 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track' => 'reload'
    = favicon_link_tag 'common/favicon.ico'
    = csrf_meta_tags

  body.web-app
    #header
      = render 'shared/webapp/header'
    #page-container  
      = yield
    #footer
      = render 'shared/webapp/footer'
  = yield(:js)

app/views/shared/admin/_header.html.slim
= react_component('TEST.Admin.Menu', {user_session: {logout_path: destroy_admin_session_path}})